insert into member (userId, userName, userPass, userEmail, salt) values ('ssafy', 'ssafyname', '959f98a3b80d77f23f5d38e729808aba9eb68c8d524ab139bbe9c6397e2b95b5', 'ssafy@ssafy.com', '711d6665594475aad2eff3e0d5b16b34d4baad16')

insert into board (articleNo, userId, subject, content, hit, registerTime) values (1, 'ssafy', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 'vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia', 85, '2023-02-05 12:29:54');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (2, 'ssafy', 'parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis', 'ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo', 43, '2023-09-18 06:26:03');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (3, 'ssafy', 'ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit', 'venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed', 33, '2023-06-09 04:37:52');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (4, 'ssafy', 'at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis', 'nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia', 47, '2023-03-02 11:46:18');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (5, 'ssafy', 'at turpis a pede posuere nonummy integer non velit donec diam', 'consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis', 54, '2023-10-14 18:02:44');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (6, 'ssafy', 'justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum', 'in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod', 82, '2023-07-21 02:14:07');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (7, 'ssafy', 'ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam', 'montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia', 92, '2023-06-14 13:51:08');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (8, 'ssafy', 'sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum', 'at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie', 100, '2023-05-18 06:36:20');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (9, 'ssafy', 'nisl nunc rhoncus dui vel sem sed sagittis nam congue risus', 'ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem', 38, '2023-10-25 08:15:17');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (10, 'ssafy', 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum', 'cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel', 86, '2023-09-25 05:48:27');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (11, 'ssafy', 'vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis', 'vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu', 90, '2023-08-06 14:39:17');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (12, 'ssafy', 'donec dapibus duis at velit eu est congue elementum in', 'ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum', 26, '2023-09-16 11:48:21');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (13, 'ssafy', 'vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat', 'lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget', 19, '2023-10-07 19:00:38');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (14, 'ssafy', 'mauris eget massa tempor convallis nulla neque libero convallis eget eleifend', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat', 28, '2023-07-30 11:42:01');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (15, 'ssafy', 'urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi', 'orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur', 43, '2022-11-24 18:50:41');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (16, 'ssafy', 'vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat', 'sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing', 37, '2023-08-05 09:00:10');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (17, 'ssafy', 'odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque', 'rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam', 30, '2023-05-16 07:05:09');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (18, 'ssafy', 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus', 'ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed', 52, '2023-07-18 11:55:02');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (19, 'ssafy', 'ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi', 'imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl', 84, '2023-06-13 00:39:49');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (20, 'ssafy', 'nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros', 'lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed', 87, '2023-06-19 07:54:08');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (21, 'ssafy', 'lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh', 'integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat', 28, '2023-01-15 12:00:24');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (22, 'ssafy', 'leo rhoncus sed vestibulum sit amet cursus id turpis integer', 'at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at', 27, '2023-09-07 04:59:43');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (23, 'ssafy', 'sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio', 'leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed', 60, '2023-08-29 01:51:19');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (24, 'ssafy', 'massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit', 92, '2022-12-25 00:33:26');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (25, 'ssafy', 'integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi', 'tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl', 94, '2023-07-30 21:11:49');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (26, 'ssafy', 'erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus', 'lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh', 41, '2023-02-21 13:24:02');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (27, 'ssafy', 'in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim', 83, '2023-06-24 08:45:05');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (28, 'ssafy', 'mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse', 'sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus', 16, '2023-08-09 06:22:36');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (29, 'ssafy', 'semper sapien a libero nam dui proin leo odio porttitor id', 'blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id', 23, '2023-03-19 20:53:46');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (30, 'ssafy', 'nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit', 'dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum', 68, '2023-09-08 07:05:57');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (31, 'ssafy', 'lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel', 'magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra', 98, '2023-08-01 11:04:27');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (32, 'ssafy', 'aenean fermentum donec ut mauris eget massa tempor convallis nulla neque', 'vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec', 39, '2023-07-23 07:12:39');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (33, 'ssafy', 'aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien', 'duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in', 40, '2023-07-24 20:10:26');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (34, 'ssafy', 'iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut', 'sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec', 16, '2023-08-07 11:59:30');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (35, 'ssafy', 'congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat', 'quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut', 70, '2023-07-04 23:49:26');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (36, 'ssafy', 'iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo', 'ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla', 60, '2023-09-27 17:03:19');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (37, 'ssafy', 'elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum', 'eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut', 77, '2023-05-17 23:06:16');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (38, 'ssafy', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur', 'sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing', 60, '2023-08-13 21:43:20');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (39, 'ssafy', 'felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in', 'eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio', 62, '2022-12-02 15:22:18');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (40, 'ssafy', 'est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien', 'tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum', 46, '2023-01-04 12:49:03');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (41, 'ssafy', 'id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan', 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla', 15, '2023-05-12 23:04:58');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (42, 'ssafy', 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet', 'vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel', 6, '2023-06-21 01:42:50');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (43, 'ssafy', 'a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis', 'sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel', 69, '2023-01-25 03:26:20');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (44, 'ssafy', 'diam id ornare imperdiet sapien urna pretium nisl ut volutpat', 'lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', 57, '2023-06-18 23:37:42');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (45, 'ssafy', 'in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in', 'sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 95, '2023-06-02 11:33:35');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (46, 'ssafy', 'nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper', 'luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi', 16, '2023-07-19 12:13:41');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (47, 'ssafy', 'erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam', 'hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at', 59, '2023-05-10 13:33:50');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (48, 'ssafy', 'non velit donec diam neque vestibulum eget vulputate ut ultrices', 'neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', 59, '2023-07-20 23:26:41');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (49, 'ssafy', 'consequat in consequat ut nulla sed accumsan felis ut at', 'cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus', 86, '2023-10-13 11:54:31');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (50, 'ssafy', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede', 'suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in', 61, '2023-10-11 09:09:18');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (51, 'ssafy', 'lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus', 'purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque', 19, '2023-08-08 21:27:50');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (52, 'ssafy', 'libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo', 'eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia', 23, '2023-03-04 20:08:21');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (53, 'ssafy', 'ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies', 'non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat', 24, '2023-04-14 16:45:45');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (54, 'ssafy', 'magna vulputate luctus cum sociis natoque penatibus et magnis dis', 'amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis', 25, '2023-10-07 09:37:48');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (55, 'ssafy', 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet', 'massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue', 41, '2023-04-06 07:17:25');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (56, 'ssafy', 'congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero', 'scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla', 59, '2023-01-28 11:54:33');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (57, 'ssafy', 'lorem quisque ut erat curabitur gravida nisi at nibh in hac', 'volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor', 78, '2023-07-03 21:15:06');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (58, 'ssafy', 'odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est', 'posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere', 44, '2023-09-09 03:32:11');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (59, 'ssafy', 'ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu', 'in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non', 41, '2023-01-27 03:45:27');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (60, 'ssafy', 'mi nulla ac enim in tempor turpis nec euismod scelerisque', 'magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus', 86, '2023-01-03 07:26:30');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (61, 'ssafy', 'pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed', 'mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce', 69, '2023-05-31 03:06:37');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (62, 'ssafy', 'porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris', 'sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse', 66, '2023-05-06 08:40:13');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (63, 'ssafy', 'semper porta volutpat quam pede lobortis ligula sit amet eleifend pede', 'aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed', 70, '2023-05-12 20:34:31');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (64, 'ssafy', 'vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit', 'in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales', 74, '2023-04-03 11:15:16');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (65, 'ssafy', 'et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc', 'mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque', 83, '2023-04-19 19:02:01');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (66, 'ssafy', 'leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam', 'ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl', 38, '2023-02-02 12:56:16');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (67, 'ssafy', 'blandit non interdum in ante vestibulum ante ipsum primis in faucibus', 'in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh', 87, '2023-09-23 06:47:21');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (68, 'ssafy', 'primis in faucibus orci luctus et ultrices posuere cubilia curae', 'lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus', 98, '2023-02-15 04:32:42');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (69, 'ssafy', 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in', 'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus', 75, '2023-06-22 23:50:00');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (70, 'ssafy', 'quisque porta volutpat erat quisque erat eros viverra eget congue', 'faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et', 54, '2023-03-03 11:10:09');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (71, 'ssafy', 'elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue', 'sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in', 1, '2023-08-25 05:33:40');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (72, 'ssafy', 'tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia', 'felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu', 59, '2023-09-04 08:44:37');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (73, 'ssafy', 'in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla', 'ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum', 9, '2023-02-12 08:10:51');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (74, 'ssafy', 'odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est', 'pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc', 36, '2023-07-27 01:35:52');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (75, 'ssafy', 'purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor', 'vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit', 77, '2023-09-30 11:52:17');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (76, 'ssafy', 'duis aliquam convallis nunc proin at turpis a pede posuere nonummy', 'ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc', 37, '2023-09-25 00:51:54');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (77, 'ssafy', 'in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', 'leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero', 43, '2023-06-17 03:27:04');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (78, 'ssafy', 'morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in', 'libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes', 74, '2023-02-26 01:24:27');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (79, 'ssafy', 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut', 'nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse', 36, '2023-08-28 05:50:38');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (80, 'ssafy', 'blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla', 'augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus', 90, '2023-06-28 12:17:53');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (81, 'ssafy', 'suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae', 'quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam', 16, '2023-06-12 14:36:42');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (82, 'ssafy', 'a odio in hac habitasse platea dictumst maecenas ut massa', 'sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris', 56, '2023-06-06 01:11:07');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (83, 'ssafy', 'pede venenatis non sodales sed tincidunt eu felis fusce posuere felis', 'suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat', 23, '2023-11-01 08:50:15');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (84, 'ssafy', 'non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse', 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac', 57, '2023-04-30 19:14:52');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (85, 'ssafy', 'convallis nunc proin at turpis a pede posuere nonummy integer non velit donec', 'sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla', 32, '2023-04-18 01:54:49');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (86, 'ssafy', 'magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque', 'in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum', 12, '2023-07-23 03:40:33');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (87, 'ssafy', 'nulla tellus in sagittis dui vel nisl duis ac nibh', 'vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem', 86, '2023-05-10 13:21:55');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (88, 'ssafy', 'ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc', 'eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet', 7, '2022-12-22 23:15:07');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (89, 'ssafy', 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id', 'ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus', 26, '2023-03-19 14:29:18');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (90, 'ssafy', 'sed nisl nunc rhoncus dui vel sem sed sagittis nam congue', 'ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum', 73, '2023-09-18 23:58:56');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (91, 'ssafy', 'quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum', 'feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu', 39, '2023-07-10 10:53:43');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (92, 'ssafy', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 'lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique', 76, '2023-06-24 20:07:45');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (93, 'ssafy', 'amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis', 'dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis', 35, '2023-02-28 21:54:53');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (94, 'ssafy', 'amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur', 'tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in', 62, '2023-02-04 12:36:28');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (95, 'ssafy', 'nulla elit ac nulla sed vel enim sit amet nunc viverra', 'nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue', 20, '2022-12-29 02:55:29');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (96, 'ssafy', 'ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin', 'faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec', 41, '2023-05-11 05:46:26');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (97, 'ssafy', 'libero rutrum ac lobortis vel dapibus at diam nam tristique', 'vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur', 27, '2022-12-13 09:21:19');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (98, 'ssafy', 'cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit', 'potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et', 2, '2023-08-18 03:39:32');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (99, 'ssafy', 'eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur', 'est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim', 95, '2023-05-03 07:11:08');
insert into board (articleNo, userId, subject, content, hit, registerTime) values (100, 'ssafy', 'massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida', 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula', 12, '2023-09-03 01:06:07');


insert into tripplan (planId, planName) values (1, '테스트1');
insert into tripplan (planId, planName) values (2, '테스트2');
insert into tripplan (planId, planName) values (3, '테스트3');
insert into tripplan (planId, planName) values (4, '테스트4');
insert into tripplan (planId, planName) values (5, '테스트5');


insert into tripcourse (courseId, planId, userId, addressName, categoryGroupName, placeName, placeUrl, roadAddressName, x, y)
values (1, 1, 'ssafy', '서울 용산구 이태원동 34-149',
        '음식점', '명동교자 이태원점','http://place.map.kakao.com/1952478679', '서울 용산구 녹사평대로 136',
        '126.990949104616','37.5308561175718');
insert into tripcourse (courseId, planId, userId, addressName, categoryGroupName, placeName, placeUrl, roadAddressName, x, y)
values (2, 1, 'ssafy', '서울 용산구 이태원동 181-8',
        '음식점', '바토스 이태원점','http://place.map.kakao.com/21535686', '서울 용산구 이태원로15길 1',
        '126.990174761387','37.5346042203356');
insert into tripcourse (courseId, planId, userId, addressName, categoryGroupName, placeName, placeUrl, roadAddressName, x, y)
values (3, 1, 'ssafy', '서울 용산구 이태원동 457-1',
        '음식점', '부다스벨리','http://place.map.kakao.com/17011339', '서울 용산구 녹사평대로40길 48',
        '126.9883690507292','37.53438961809852');
insert into tripcourse (courseId, planId, userId, addressName, categoryGroupName, placeName, placeUrl, roadAddressName, x, y)
values (4, 1, 'ssafy', '서울 용산구 이태원동 127-28',
        '음식점', '로우앤슬로우','http://place.map.kakao.com/1376253571', '서울 용산구 보광로 126',
        '126.99421849699539','37.53401162895581');
insert into tripcourse (courseId, planId, userId, addressName, categoryGroupName, placeName, placeUrl, roadAddressName, x, y)
values (5, 1, 'ssafy', '서울 용산구 이태원동 172-2',
        '음식점', '오리지널팬케이크하우스 이태원점','http://place.map.kakao.com/27462552', '서울 용산구 이태원로 153',
        '126.99103917462925','37.53452500101547');